version: '3.1'
services :
  db:
    image: postgres:9.6.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: todoapp
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8081:8080
